image: atlassian/default-image:3

pipelines:

  custom:
    build-and-deploy-to-production:
      - step:
          name: Build the Astro Project
          script:
            - npm run build
      - step:
          name: Deploy to Production
          script:
            - git remote add uberspace ssh://lokr@lynx.uberspace.de/home/lokr/notenentwickler.com.git
            - git push uberspace master
