image: atlassian/default-image:3

pipelines:

  custom:
    build-and-deploy-to-production:
      - step:
          name: Build the Astro Project
          script:
            - npm install
            - npm run build
      - step:
          name: Deploy to Production
          script:
            - git remote add uberspace ssh://lokr@lynx.uberspace.de/home/lokr/notenentwickler.com.git
            - git push uberspace master
            
            
    build-and-deploy-ftp:
      - step:
          name: Deploy to Production
          deployment: production
          script:
            - pipe: atlassian/ftp-deploy:0.4.0
              variables:
                USER: $FTP_USERNAME
                PASSWORD: $FTP_PASSWORD
                SERVER: $FTP_HOST
                REMOTE_PATH: /var/www/virtual/lokr/html
                LOCAL_PATH: dist/assets

