image: atlassian/default-image:3

pipelines:

  custom:
    deploy-to-production:
      - step:
          name: Deploy to Production
          deployment: production
          script:
            - pipe: atlassian/ftp-deploy:0.4.0
              variables:
                USER: $FTP_USERNAME
                PASSWORD: $FTP_PASSWORD
                SERVER: $FTP_HOST
                REMOTE_PATH: /var/www/virtual/lokr/notenentwickler.com.master
                EXTRA_ARGS: "--exclude=.bitbucket/ --exclude=.git/ --exclude=bitbucket-pipelines.yml --exclude=.gitignore" # Ignore these
