image: atlassian/default-image:3

pipelines:

  custom:
    build-and-deploy-to-production:
      - step:
          name: Build the Astro Project
          script:
            - npm install
            - npm run build
      - step:
          name: Deploy to Production
          script:
            - git remote add uberspace ssh://lokr@lynx.uberspace.de/home/lokr/notenentwickler.com.git
            - git push uberspace master
            
            
    build-and-deploy-sftp:
      - step:
          name: Deploy to Production
          script:
            - pipe: atlassian/sftp-deploy:0.5.11
              variables:
                USER: $FTP_USERNAME
                SERVER: '95.143.172.147'
                PASSWORD: $FTP_PASSWORD
                REMOTE_PATH: '/var/www/virtual/lokr/html/'
                LOCAL_PATH: 'dist'
                DEBUG: 'true'

